// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "dairlib_lcmt_robot_output.h"

static int __dairlib_lcmt_robot_output_hash_computed;
static uint64_t __dairlib_lcmt_robot_output_hash;

uint64_t __dairlib_lcmt_robot_output_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __dairlib_lcmt_robot_output_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __dairlib_lcmt_robot_output_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xaa780c82226ac6e0LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __dairlib_lcmt_robot_output_get_hash(void)
{
    if (!__dairlib_lcmt_robot_output_hash_computed) {
        __dairlib_lcmt_robot_output_hash = (int64_t)__dairlib_lcmt_robot_output_hash_recursive(NULL);
        __dairlib_lcmt_robot_output_hash_computed = 1;
    }

    return __dairlib_lcmt_robot_output_hash;
}

int __dairlib_lcmt_robot_output_encode_array(void *buf, int offset, int maxlen, const dairlib_lcmt_robot_output *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_positions), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_velocities), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_efforts), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, p[element].position_names, p[element].num_positions);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].position, p[element].num_positions);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, p[element].velocity_names, p[element].num_velocities);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].velocity, p[element].num_velocities);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, p[element].effort_names, p[element].num_efforts);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].effort, p[element].num_efforts);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].imu_accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int dairlib_lcmt_robot_output_encode(void *buf, int offset, int maxlen, const dairlib_lcmt_robot_output *p)
{
    int pos = 0, thislen;
    int64_t hash = __dairlib_lcmt_robot_output_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __dairlib_lcmt_robot_output_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __dairlib_lcmt_robot_output_encoded_array_size(const dairlib_lcmt_robot_output *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_positions), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_velocities), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_efforts), 1);

        size += __string_encoded_array_size(p[element].position_names, p[element].num_positions);

        size += __double_encoded_array_size(p[element].position, p[element].num_positions);

        size += __string_encoded_array_size(p[element].velocity_names, p[element].num_velocities);

        size += __double_encoded_array_size(p[element].velocity, p[element].num_velocities);

        size += __string_encoded_array_size(p[element].effort_names, p[element].num_efforts);

        size += __double_encoded_array_size(p[element].effort, p[element].num_efforts);

        size += __double_encoded_array_size(p[element].imu_accel, 3);

    }
    return size;
}

int dairlib_lcmt_robot_output_encoded_size(const dairlib_lcmt_robot_output *p)
{
    return 8 + __dairlib_lcmt_robot_output_encoded_array_size(p, 1);
}

int __dairlib_lcmt_robot_output_decode_array(const void *buf, int offset, int maxlen, dairlib_lcmt_robot_output *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_positions), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_velocities), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_efforts), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].position_names = (char**) lcm_malloc(sizeof(char*) * p[element].num_positions);
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, p[element].position_names, p[element].num_positions);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].position = (double*) lcm_malloc(sizeof(double) * p[element].num_positions);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].position, p[element].num_positions);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].velocity_names = (char**) lcm_malloc(sizeof(char*) * p[element].num_velocities);
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, p[element].velocity_names, p[element].num_velocities);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].velocity = (double*) lcm_malloc(sizeof(double) * p[element].num_velocities);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].velocity, p[element].num_velocities);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].effort_names = (char**) lcm_malloc(sizeof(char*) * p[element].num_efforts);
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, p[element].effort_names, p[element].num_efforts);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].effort = (double*) lcm_malloc(sizeof(double) * p[element].num_efforts);
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].effort, p[element].num_efforts);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].imu_accel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __dairlib_lcmt_robot_output_decode_array_cleanup(dairlib_lcmt_robot_output *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_positions), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_velocities), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_efforts), 1);

        __string_decode_array_cleanup(p[element].position_names, p[element].num_positions);
        if (p[element].position_names) free(p[element].position_names);

        __double_decode_array_cleanup(p[element].position, p[element].num_positions);
        if (p[element].position) free(p[element].position);

        __string_decode_array_cleanup(p[element].velocity_names, p[element].num_velocities);
        if (p[element].velocity_names) free(p[element].velocity_names);

        __double_decode_array_cleanup(p[element].velocity, p[element].num_velocities);
        if (p[element].velocity) free(p[element].velocity);

        __string_decode_array_cleanup(p[element].effort_names, p[element].num_efforts);
        if (p[element].effort_names) free(p[element].effort_names);

        __double_decode_array_cleanup(p[element].effort, p[element].num_efforts);
        if (p[element].effort) free(p[element].effort);

        __double_decode_array_cleanup(p[element].imu_accel, 3);

    }
    return 0;
}

int dairlib_lcmt_robot_output_decode(const void *buf, int offset, int maxlen, dairlib_lcmt_robot_output *p)
{
    int pos = 0, thislen;
    int64_t hash = __dairlib_lcmt_robot_output_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __dairlib_lcmt_robot_output_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int dairlib_lcmt_robot_output_decode_cleanup(dairlib_lcmt_robot_output *p)
{
    return __dairlib_lcmt_robot_output_decode_array_cleanup(p, 1);
}

int __dairlib_lcmt_robot_output_clone_array(const dairlib_lcmt_robot_output *p, dairlib_lcmt_robot_output *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int32_t_clone_array(&(p[element].num_positions), &(q[element].num_positions), 1);

        __int32_t_clone_array(&(p[element].num_velocities), &(q[element].num_velocities), 1);

        __int32_t_clone_array(&(p[element].num_efforts), &(q[element].num_efforts), 1);

        q[element].position_names = (char**) lcm_malloc(sizeof(char*) * q[element].num_positions);
        __string_clone_array(p[element].position_names, q[element].position_names, p[element].num_positions);

        q[element].position = (double*) lcm_malloc(sizeof(double) * q[element].num_positions);
        __double_clone_array(p[element].position, q[element].position, p[element].num_positions);

        q[element].velocity_names = (char**) lcm_malloc(sizeof(char*) * q[element].num_velocities);
        __string_clone_array(p[element].velocity_names, q[element].velocity_names, p[element].num_velocities);

        q[element].velocity = (double*) lcm_malloc(sizeof(double) * q[element].num_velocities);
        __double_clone_array(p[element].velocity, q[element].velocity, p[element].num_velocities);

        q[element].effort_names = (char**) lcm_malloc(sizeof(char*) * q[element].num_efforts);
        __string_clone_array(p[element].effort_names, q[element].effort_names, p[element].num_efforts);

        q[element].effort = (double*) lcm_malloc(sizeof(double) * q[element].num_efforts);
        __double_clone_array(p[element].effort, q[element].effort, p[element].num_efforts);

        __double_clone_array(p[element].imu_accel, q[element].imu_accel, 3);

    }
    return 0;
}

dairlib_lcmt_robot_output *dairlib_lcmt_robot_output_copy(const dairlib_lcmt_robot_output *p)
{
    dairlib_lcmt_robot_output *q = (dairlib_lcmt_robot_output*) malloc(sizeof(dairlib_lcmt_robot_output));
    __dairlib_lcmt_robot_output_clone_array(p, q, 1);
    return q;
}

void dairlib_lcmt_robot_output_destroy(dairlib_lcmt_robot_output *p)
{
    __dairlib_lcmt_robot_output_decode_array_cleanup(p, 1);
    free(p);
}

int dairlib_lcmt_robot_output_publish(lcm_t *lc, const char *channel, const dairlib_lcmt_robot_output *p)
{
      int max_data_size = dairlib_lcmt_robot_output_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = dairlib_lcmt_robot_output_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _dairlib_lcmt_robot_output_subscription_t {
    dairlib_lcmt_robot_output_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void dairlib_lcmt_robot_output_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    dairlib_lcmt_robot_output p;
    memset(&p, 0, sizeof(dairlib_lcmt_robot_output));
    status = dairlib_lcmt_robot_output_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding dairlib_lcmt_robot_output!!!\n", status);
        return;
    }

    dairlib_lcmt_robot_output_subscription_t *h = (dairlib_lcmt_robot_output_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    dairlib_lcmt_robot_output_decode_cleanup (&p);
}

dairlib_lcmt_robot_output_subscription_t* dairlib_lcmt_robot_output_subscribe (lcm_t *lcm,
                    const char *channel,
                    dairlib_lcmt_robot_output_handler_t f, void *userdata)
{
    dairlib_lcmt_robot_output_subscription_t *n = (dairlib_lcmt_robot_output_subscription_t*)
                       malloc(sizeof(dairlib_lcmt_robot_output_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 dairlib_lcmt_robot_output_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg dairlib_lcmt_robot_output LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int dairlib_lcmt_robot_output_subscription_set_queue_capacity (dairlib_lcmt_robot_output_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int dairlib_lcmt_robot_output_unsubscribe(lcm_t *lcm, dairlib_lcmt_robot_output_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe dairlib_lcmt_robot_output_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

